openapi: 3.0.0
info:
  description: This is the REST API for OpenPetID
  version: "1.0.0"
  title: OpenPetID API
  contact:
    email: contact@jonzlotnik.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: owners
    description: Operations for authenticated pet owners to manage their pets.
  - name: public
    description: Operations available to anyone.
paths:
  /pets/{petId}:
    get:
      tags:
        - owners
      summary: Get pet data.
      operationId: getPet
      description: |
        Returns all data stored under the pet's UID.
      parameters:
        - in: path
          name: petId
          description: Pet UID.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InventoryItem'
        '400':
          description: bad input parameter
    put:
      tags:
        - owners
      summary: Updates pet data
      operationId: updatePet
      description: Adds an item to the system
      responses:
        '201':
          description: item updated
        '400':
          description: 'invalid input, object invalid'
      parameters:
        - in: path
          name: petId
          description: Pet UID.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryItem'
        description: Inventory item to add

servers:
  - url: 'https://virtserver.swaggerhub.com/jonZlotnik/OpenPetID/1.0.0'
  - url: 'https://openpetid-apim.azure-api.net/v1'
components:
  schemas:
    InventoryItem:
      type: object
      required:
        - id
        - name
        - manufacturer
        - releaseDate
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Widget Adapter
        releaseDate:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        manufacturer:
          $ref: '#/components/schemas/Manufacturer'
    Manufacturer:
      required:
        - name
      properties:
        name:
          type: string
          example: ACME Corporation
        homePage:
          type: string
          format: url
          example: 'https://www.acme-corp.com'
        phone:
          type: string
          example: 408-867-5309